# Generated by Django 4.2.5 on 2023-09-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_publish_data_blogpost_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
